[env:native]
platform = native
build_flags = -std=gnu++17
test_framework = unity

[env:rpipico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git#79ce473e1a8010ed8096388690222fd2c94858a6
board = rpipico
framework = arduino
board_build.core = earlephilhower
board_build.filesystem = littlefs
board_build.filesystem_size = 1m
upload_protocol = picotool
platform_packages =
    framework-arduinopico @ https://github.com/earlephilhower/arduino-pico/releases/download/5.6.0/rp2040-5.6.0.zip

build_flags =
    -std=gnu++17

monitor_speed = 115200
monitor_filters = colorize, time

[env:rpipico2]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git#79ce473e1a8010ed8096388690222fd2c94858a6
board = rpipico2
framework = arduino
board_build.core = earlephilhower
board_build.filesystem = littlefs
board_build.filesystem_size = 1m
upload_protocol = picotool
platform_packages =
    framework-arduinopico @ https://github.com/earlephilhower/arduino-pico/releases/download/5.6.0/rp2040-5.6.0.zip

build_flags =
    -std=gnu++17

monitor_speed = 115200
monitor_filters = colorize, time

[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
board_build.filesystem = littlefs
build_flags =
    -std=gnu++17

monitor_speed = 115200
monitor_filters = colorize, time
